# Generated by Django 6.0.5 on 2026-06-25 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyAccount',
            fields=[
                ('verify_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verify_code', models.CharField(max_length=6)),
                ('verify_status', models.CharField(choices=[('UNVERIFIED', 'UNVERIFIED'), ('VERIFIED', 'VERIFIED'), ('LOCKED', 'LOCKED')], default='UNVERIFIED', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('verify_time', models.DateTimeField(blank=True, null=True)),
                ('lock_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='verify_accounts', to='accounts.account')),
            ],
            options={
                'db_table': 'verify_account',
            },
        ),
    ]
